name: pyLint

on: push

jobs:
  PEP8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install black
        run: |
          pip install black isort autoflake
      - name: lint with isort and black
        run: |
          black *
          isort *
          autoflake --in-place --recursive --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports *
      # commit changes
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'pyLint: auto-fixes'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: 1Danish-00
          commit_user_email: danish@ultroid.tech
          commit_author: 1Danish-00 <danish@ultroid.tech>
